version: '3.4'
services:
  vihdas:
    image: vihdas
    hostname: vihdas
    restart: always
    depends_on:
      - postgres
    container_name: vihdas
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://cachorro_cami:Tengo1amo@cluster0.ffbyjzl.mongodb.net/?retryWrites=true&w=majority
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:Tengo1amo@postgres:5432/RyS?schema=public
    expose:
      - 3000
    networks:
      - internal

networks:
  internal:
    external: true
    name: internal
